spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: @datasource.url@
      username: @datasource.username@
      password: @datasource.password@
      initial-size: @datasource.initial-size@
      max-active: @datasource.max-active@
      min-evictable-idle-time-millis: 100000
      validation-query: select 1
#Mapper通用插件
mapper:
  mappers: com.MyMapper
  not-empty: false
  identity: MYSQL
#MyBatis配置
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
